#!/bin/bash

tmpdir=$(mktemp -d)
cd "$tmpdir"
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
tar xzf nvim-macos-arm64.tar.gz
rm -rf "$HOME/.local/neovim"
mv ./nvim-macos-arm64/ "$HOME/.local/neovim"
rm -rf "$tmpdir"
